### ISSUE TITLE
Where do you find the output files on macOS?

### ISSUE THREAD

**Issue by intersctellar** [Mincka/DMArchiver#13]
First of all, I want to thank you so much for creating this tool. No one on the internet did this but you. Its my 1 year anniversary with my girlfriend and i really want to retrieve a string of messages because i'm planning to gift her something and it is important that i have all the dms archived. Unfortunately i'm very bad at coding and i couldn't understand the instructions. I think my convo id is 853339611514507267, do i have to type my user name & pass then enter this $ dmarchiver -id "853339611514507267" or is there something i am missing. also where do the messages end up? i do realize how stupid this whole question might be but i'd be grateful if you could assist me. Thank you so much.

**Comment by Mincka** [comment]
Hi,

You just can run the tool without arguments to retrieve all your conversations (starting with the 50 most recent ones). If you run the script using the Terminal as explained in the Readme, the files will be written to your `/users/your-user-name/Downloads` folder. If you just click on the tool, the files will be written in `/users/you-user-name/`. The conversations are written only once all the messages have been retrieved from Twitter.

Note: This answer has been given to the user via Twitter DM. He broke the known record of tweets in a single one-to-one conversation, with **171428** tweets. :)
