### ISSUE TITLE
How to get the out text file in UTF-8 encoding?

### ISSUE THREAD

**Issue by UnicodeTF8** [Mincka/DMArchiver#25]
This works like a charm but im seeing characters like ÐŸÐ¾Ð»ÐµÐ³Ñ‡Ðµ.. which means that it dont support other languages... is there any other way to do it?

**Comment by Mincka** [comment]
The output is already in UTF-8 with support of Unicode characters like emojis. What was the original text in this tweet? Maybe you need to use a text reader which support UTF-8. In Notepad++, you need to specify the encoding otherwise it may not displayed properly.

**Comment by UnicodeTF8** [comment]
oh, i had to specify the encoding.  thank you so much for the tool. have a nice day! :)
