### ISSUE TITLE
Intermittent timeout errors

### ISSUE THREAD

**Issue by kingboyy99** [Mincka/DMArchiver#28]
this won't work. once i enter my username and password, the application crashes and doesn't provide any further information.

**Comment by Mincka** [comment]
Please provide details about the version, the OS.

A screenshot of the application execution when it starts and when it crashes could be useful.

**Comment by kingboyy99** [comment]
![dma success](https://user-images.githubusercontent.com/30593547/28857769-5c2a3b92-7769-11e7-8f01-d4b3bee6e9b3.PNG)
![dma](https://user-images.githubusercontent.com/30593547/28857770-5c86783a-7769-11e7-93f8-08ec23b1fbbe.PNG)


I have attached the screenshot of the application when it starts and right before it crashes. Also, I am using Windows 7.

**Comment by kingboyy99** [comment]
will this application download Images and GIF as they are or will it provide a link for them?

**Comment by Mincka** [comment]
Could you execute the program from a Command Prompt instead of double-clicking on the file? It may allow the error to be displayed in the window before the error message disappear.

To do so, following these instructions:
1) Windows + R
2) cmd
3) cd Desktop
4) dmarchiver

If you want to download images, and gifs, you also have to use this method, to run the tool with these arguments:
dmarchiver -di -dg

In your chat history, you will see the link to the images, but they will be downloaded at the same time in a separate folder.

**Comment by Mincka** [comment]
Actually, from what I see, the tool has detected that a previous conversation was downloaded.

Are you sure you do not have a file "57394496-882491056679530496.txt" on your desktop?

**Comment by kingboyy99** [comment]
![error](https://user-images.githubusercontent.com/30593547/28862876-54a800aa-7784-11e7-85cd-a661376c098e.PNG)

no, i do not have any file with that name. also now it is not even giving the above error but just crashes as soon as i enter password.

i have attached a screenshot for the same.

**Comment by Mincka** [comment]
Please run the tool from a new Command Prompt as explained, so I will be able to see if you have any error when the program ends. What do you mean by "the application crashes"?

Do you use SMS verification?

**Comment by kingboyy99** [comment]
![cmddmarchiver](https://user-images.githubusercontent.com/30593547/28866776-9956d390-7791-11e7-832b-2c302320addc.PNG)


when i am using the tool from command prompt, it is showing a username or password error, but i am using my twitter on my laptop, hence i am pretty sure that the username and password are correct. also, i tried using someone's account too and it was still showing the same error.

**Comment by kingboyy99** [comment]
![another error](https://user-images.githubusercontent.com/30593547/28867780-e2b79b70-7794-11e7-9428-ae44fdec7013.PNG)

here. a totally different output this time, yet again no success.

**Comment by Mincka** [comment]
Are you using the tool behind a restricted environment (at school, in enterprise, behind a proxy)? It seems the connection is very unstable.

**Comment by kingboyy99** [comment]
no, i am using the tool on home home/ personal laptop. 
what seems to be the issue due to which the tool is showing username or password error?

**Comment by Mincka** [comment]
Because you do not reach the same steps during the execution, it seems to be related to a random connection issue. Sometimes, you manage to authenticate, so it means the first request is properly managed, sometimes, you don't even manage to authenticate.

Maybe you can try over another connection, using your mobile phone as a hotspot for example.

Also, in the current version, if you use multi-factor with SMS authentication, the script will fail saying the password is incorrect. This feature is not yet supported and you may need to disable temporarily the SMS authentication.

**Comment by kingboyy99** [comment]
i do not use SMS authentication. I tried using it over a different network but it still didn't work. i am not sure why it is showing the connection issue as my internet is just a normal home WiFi.

**Comment by Mincka** [comment]
Can you try using a different computer on a different network? Just to know if it's related to your account, your computer or your network.

**Comment by goofyhsk** [comment]
> DMArchiver 0.1.6
> Running on Python 3.5.2 (v3.5.2:4def2a2901a5, Jun 25 2016, 22:18:55) [MSC v.1900
>  64 bit (AMD64)]
> 
> Authentication succeedeed.
> 
> Conversation ID not specified. Retrieving all the threads.
> Traceback (most recent call last):
>   File "dmarchiver\cmdline.py", line 95, in <module>
>   File "dmarchiver\cmdline.py", line 86, in main
>   File "dmarchiver\core.py", line 302, in get_threads
> KeyError: 'threads'
> Failed to execute script cmdline


> DMArchiver 0.1.7
> Running on Python 3.4.4 (v3.4.4:737efcadf5a6, Dec 20 2015, 19:28:18) [MSC v.1600
>  32 bit (Intel)]
> 
> Authentication succeedeed.
> 
> Press Ctrl+C at anytime to write the current conversation and skip to the next o
> ne.
>  Keep it pressed to exit the script.
> 
> Conversation ID not specified. Retrieving all the threads.
> Traceback (most recent call last):
>   File "dmarchiver\cmdline.py", line 107, in <module>
>   File "dmarchiver\cmdline.py", line 96, in main
>   File "dmarchiver\core.py", line 302, in get_threads
> KeyError: 'threads'
> Failed to execute script cmdline

**Comment by Mincka** [comment]
@goofyhsk: Seems related to updated HTML code on Twitter. Not the same kind of issue. Could you create a separate issue please? Thanks.
