### ISSUE TITLE
how do i use the commands starting with $?

### ISSUE THREAD

**Issue by kirikomori** [Mincka/DMArchiver#34]
When I open the exe it asks for my username and password. Then it archives the dms, and closes itself right after finishing.

**Comment by Mincka** [comment]
`$` is just a symbol to represent a command prompt.

Follow these instructions:
1. Use Windows + R shortcut
2. Type "cmd", enter
4. Type "cd Downloads" (if DMArchiver.exe is in your "Downloads" folder), enter
5. Type "dmarchiver -di -dg -dv", enter
