### ISSUE TITLE
Twitter account being locked due to suspected Robot

### ISSUE THREAD

**Issue by ghost** [Mincka/DMArchiver#37]
Hi, twice now when using DMArchiver I've had my Twitter account locked because they think I'm using a robot (which I am, technically) to do something bad (which I'm not).

Both times it's easy to unlock using ReCaptcha or SMS code - I'm assuming it's because of the speed of the requests being made.

Would it be possible to add an optional argument to introduce a delay between requests, to more closely resemble normal browser action?

eg. **-td 10**  (10 second delay between requests)

Thanks for an excellent program.

**Comment by Mincka** [comment]
Hi,
Did you have this issue using the versions 0.1.9 or 0.2.0?

The previous versions may be stuck in an infinite loop because of an update in the Twitter code.

Anyway, I will add a parameter to add a delay for the conversation and message retrieval loops.

**Comment by ghost** [comment]
Can only say 0.1.9, it happened today when I ran it then I saw you had updated to 0.2.0 (about 5 hours beforehand).
I've run 0.2.0 once and it worked but it took a dozen or so runs of 0.1.9 before the problem first appeared.

Thank you for the option.

**Comment by ghost** [comment]
Just an update to this, I had my account blocked while using 0.2.0 to download new messages yesterday.

Forgot to pause the CLI window so didn't catch the error.

**Comment by Mincka** [comment]
-d / --delay option implemented in 0.2.1 a8fe118c202315417471586b4c956f3098fa1047
