### ISSUE TITLE
twitter account getting locked

### ISSUE THREAD

**Issue by pj267** [Mincka/DMArchiver#40]
my twitter account is being locked eachtime I use dmarchiver

**Comment by Elhazet** [comment]
Same here. No downloads possible anymore, no matter which version is used.

**Comment by Mincka** [comment]
Could you tell me at which moment the script stops its execution? Is it before the login, before the retrieval of the conversations or during the crawl of one of the conversations?

**Comment by Elhazet** [comment]
In my case it happens immediately. It looks like a "normal" crash but at the login moment (in fact, just after I' m getting the message there was a login from a firefox browser) my Twitter account immediately locks. No crawling at all. 
Using Windows 7 and 10 with version 2.0 and earlier.

**Comment by Mincka** [comment]
I think I need to update the user-agent in the requests but for the login, it's a bit a tricky part. The only automated login I was able to perform was with a Firefox user-agent, on the mobile version...

For some reason (maybe some antibot protection), I was not able to make the script get a valid session with other browsers on this form and no browser at all on the main login form.

I need to investigate and implement the delay between requests (#37).

**Comment by Mincka** [comment]
Latest version has a -d / --delay option to slow down the tool.
User-agent are more recent and more appropriate depending on the used platform (OS)
Unlocking an account and attempt to run the script just after seems to be always successful in my case.
Other options may be investigated in another issue to keep cookies locally. #42
