### ISSUE TITLE
0.2.0 is not running

### ISSUE THREAD

**Issue by rj8709** [Mincka/DMArchiver#41]
version 0.2.0 is not running on my 32 bit os windows

**Comment by Mincka** [comment]
Do you have any error message? Which Windows version do you have?

**Comment by rj8709** [comment]
i have 32 bit windows and yes it shows a error and it says that the version of your computer is not compatible with this version of dmarchiver

**Comment by Mincka** [comment]
Indeed, there was an issue with the compilation of this version for Windows.

It should have been compiled with Python 3.4 for Windows 32 bits. I have reuploaded the 32-bits release. 

Please try with this one: https://github.com/Mincka/DMArchiver/releases/download/0.2.0/dmarchiver-0.2.0-windows-x86-32.zip
