### ISSUE TITLE
Request: Save twitter user names?

### ISSUE THREAD

**Issue by Prisoner416** [Mincka/DMArchiver#43]
Would it be possible to have the program save the @ twitter id of the people I have conversations with, perhaps at the top of the log? It would help me jump to those conversations with searches and id those that deactivate.

**Comment by Mincka** [comment]
I have one issue with the Twitter handle, it can be modified at any time. Another issue with groups is that people can be added to the group at any time. Consequently, it can be complicated to keep an up-to-date header at the top of the file with the list of people in the conversations.

Maybe I can generate and overwrite an index file to get a quick mapping between the conversations ids and the people in the conversations at the time of the execution.

I don't understand your last statement "id those that deactivate.". What do you want to do? Download the messages of a restricted number of threads? The tool does not currently support a list of conversations but it could be also an easy improvement I guess.

**Comment by Prisoner416** [comment]
What I meant by ID is simply that I do a lot of RP on twitter, and several cases have occurred where accounts have been disabled by twitter or deleted by the owner. So, having the @ name or twitter url would be helpful, for sorting on my end or for easily jumping from an archive to the live page to see if it's updated. 

Basically, right now I understand the limits with the files names being numbers, so I use Agent Ransack to search for various names of users. Having the twitter url/@ would make it super simple to search with that method.

**Comment by trwnh** [comment]
seconding this. several of my friends' accounts have emoji display names that don't really identify who they are, whereas their handles are easily identifiable. an older version of this tool saved both display name and username, so it's sad to see that functionality be removed...

**Comment by trwnh** [comment]
Is there a way to get both usernames AND display names? @Mincka

**Comment by Mincka** [comment]
You can if you concatenate yourself the two parts in the code. I will not implement it as an option, I think it would be to messy to have both at the same time.
