### ISSUE TITLE
Code 131: Internal error

### ISSUE THREAD

**Issue by nomicode** [Mincka/DMArchiver#46]
I am trying this tool out but I get the same error each time:

```
Previous conversation not found. Creating a new one with incremental support.
An error occured during the parsing of the tweets.

Twitter error details below:
Code 131: Internal error
```

**Comment by CCpt5** [comment]
I had been using this tool and then received this error tonight when I tried to run it from memory (I just ran dmarchive.exe and entered credentials @ name).

What did work was to use the options to download images/videos and my email (not my @ name).

So 

dmarchiver -dv -di

Then my email login.

I hope that helps you - great little tool.
