### ISSUE TITLE
Crashes after login

### ISSUE THREAD

**Issue by Elhazet** [Mincka/DMArchiver#50]
After login, DMArchiver crashed several times. Using my @_name eventually worked but then it began crawling from the very beginning. 
This is a very long DM conversation (2 years (!) now), so Twitter did not like that and locked my account.

I only needed an incremental update to get the last two weeks of this conversation. Hope this will be possible soon. (Windows 7)

**Comment by Mincka** [comment]
Hi, what do you mean by "it crashed"? Do you have any error message?

For your lockout issue, try to run it with the parameter "-s". You should not have additional lockouts after the first one.

The crawling starts from the latest tweets to the oldest ones. Incremental update is automatic when possible.

**Comment by Elhazet** [comment]
Hi, by "it crashed" I mean that the window closes en DMArchiver stops, just the way it does after a failed login.  
This went so quickly that I couldn't read any error message. 

Now, after a few failed logins, it also did while it was already 15-20 minutes working. 
I guess Twitter didn't like that.

Also my conversationpartner lost my DM's for about 12 hours after this happened. That was a bit scary for me. But they're back now. :)

**Comment by Mincka** [comment]
Use the tool in a Command Prompt (Windows) or Terminal (macos) like this:
`dmarchiver -s -t 5`

It will slow down the script (5-seconds pause between requests) and keep the session cookies between the runs.

**Comment by Elhazet** [comment]
It worked. Thanks a lot!
