### ISSUE TITLE
Application does not open on Windows 10 because it is detected as a virus

### ISSUE THREAD

**Issue by myNameIsRoss** [Mincka/DMArchiver#52]
On opening DMArchiver.exe :
"Operation did not complete successfully because the file contains a virus or potentially unwanted software."

**Comment by Mincka** [comment]
Hi,
I also have an up-to-date Windows 10 and do not have this error. I saw on the Internet that someone has this kind of issue when attempting to open any kind of exe files.

Do you have any dedicated anti-virus software? Did you try to run it on another computer?

**Comment by myNameIsRoss** [comment]
Hi Julien,

I don't have any dedicated antivirus, it was Windows Defender that was 
preventing me. I solved it by extracting the file and then quickly 
making an exception for it in Defender. The program worked great, thank 
you. But I'm not sure my PC flagged it as harmful. This is my first 
issue raised on GitHub ever and I'll be happy to help you, I can see if 
there's similar blocking of other exe files. My only other PC is running 
Windows 7.

**Comment by Mincka** [comment]
Thank you for the details.

I got the same issue today (detected as Trojan:Win32/Azden.B!cl) and saw that other people encountered the issue too. 😞 

I submitted a report to Microsoft for the false positive detection.

**Comment by Mincka** [comment]
Seems to be fixed now.
