### ISSUE TITLE
Command not found 

### ISSUE THREAD

**Issue by patatonix** [Mincka/DMArchiver#54]
Hi, I´m kind of a newbie with all this GitHub stuff so I'm probably doing something wrong at a very basic level but, with Python installed, the Terminal says command not found when executing $ cd Downloads
$ ./dmarchiver on it.

Any helping hand? I really need this to work.

**Comment by Mincka** [comment]
Hi,
You don't need to have Python installed. Just download the latest release here for Windows: https://github.com/Mincka/DMArchiver/releases/download/0.2.4/dmarchiver-0.2.4-windows-x86-32.zip or here for macOS: https://github.com/Mincka/DMArchiver/releases/download/0.2.4/dmarchiver-0.2.4-macos-x86-64.zip

Extract the archive and run it.

**Comment by patatonix** [comment]
Hi! I did, but when introducing the command on Terminal it says it couldn't be found
