### ISSUE TITLE
"Deleted" DMs

### ISSUE THREAD

**Issue by Angie999888** [Mincka/DMArchiver#55]
I just tried DM Archiver, and I thought it was very straightforward and easy to use - thank you for offering the software.  I do have a question for you though.  Twitter deleted all of my DMs without warning yesterday and I'm pretty upset about it.  I hadn't run into a decent archiver (yours) until that happened.  Your program pulled all of my DMs I received after Twitter dumped everything, but SnapBird was able to pull things that APPEAR to be deleted.  However, Snapbird will only pull the last 200 messages.  Is there a way DM Archiver can pull those as well or if it's not in the current visible DM dialog box, it's not accessible?   Hope that makes sense, and thank you for your time!

**Comment by Mincka** [comment]
Sorry but this cannot recover deleted tweets.

**Comment by Angie999888** [comment]
Thank you for getting back to me!!  Have a good day!

    On Sunday, October 21, 2018, 3:08:38 PM EDT, Julien Ehrhart <notifications@github.com> wrote:  
 
 
Sorry but this cannot recover deleted tweets.
