### ISSUE TITLE
Deleted DMs don’t show up. 

### ISSUE THREAD

**Issue by cb19** [Mincka/DMArchiver#57]
I’ve got the latest version and when I run it all that’s coming up is my active DMs. None of my deleted ones are showing up. I’ve tried running the program a few times now. Every time it’s the same. Snapbird is only giving me the last 200 deleted but what I’m looking for is before that.

**Comment by Mincka** [comment]
This tool will not help you to retrieve deleted DMs, sorry.

**Comment by cb19** [comment]
Ok. That’s what I was hoping to find. Thanks.
