### ISSUE TITLE
Windows detects Trojan:Win32/Ditertag.B

### ISSUE THREAD

**Issue by trwnh** [Mincka/DMArchiver#60]
Updated to latest version and suddenly Windows Defender is detecting this as a trojan. Not sure what changed between 0.2.4 and 0.2.5 to cause this. Redownloading 0.2.4 and running that doesn't trip Defender.

**Comment by Mincka** [comment]
Again... 😢 I don't know if this could be related to the fact that the `requests` dependency has a vulnerability discovered recently. I have to update it and request a white listing of defender again.

**Comment by Mincka** [comment]
Closing because it looks like it is not detected anymore as a trojan.
