### ISSUE TITLE
App closes when trying to use it + account suspension

### ISSUE THREAD

**Issue by sahlofolina** [Mincka/DMArchiver#62]
I don't know if this is a problem caused by something I'm doing wrong, any change on twitter or other users have experienced it as well, but whenever I try to use the tool, once I've entered my user and password, it stays for few seconds and then it closes. When I try multiple times, Twitter suspends my account under suspicious activity. Is there anything I'm doing wrong or any way to bypass this?

**Comment by StackmyBCHup** [comment]
update your twitter password to ensure it is correct, copy the exe file to temp fold, then run it from cmd

**Comment by Mincka** [comment]
And use `dmarchiver -s` from the Command Prompt. It will reuse an existing session.
The first time, the account may be locked but it will work the second time.

**Comment by rexetsacerdos** [comment]
Hi Mincka, We wonder whether the tools can be used without triggering the 'suspicious activity lock' one of the other developers mentioned. NB: We had scripted our own Python and Pattern tools four years ago, but are always on the lookout for smart Github Off-the-shelf solutions from the developer community.

**Comment by rexetsacerdos** [comment]
Hi Mincka, We wonder whether the tools can be used without triggering the 'suspicious activity lock' one of the other developers mentioned. NB: We had scripted our own Python and Pattern tools six years ago, but are always on the lookout for smart Github Off-the-shelf solutions from the developer community.

**Comment by Mincka** [comment]
You can use this kind of alternative for this need:
https://github.com/FlameWolf/LoadDirectMessages

Regarding Twitter, you will not be able to prevent this kind of warning since you create a new session. The only way would be to reuse your own session by crafting the session.dat file (used by -s) with the cookie from your current browser session.
