### ISSUE TITLE
"Connection reset by peer" probably caused by legacy TLS

### ISSUE THREAD

**Issue by OrangeNote** [Mincka/DMArchiver#67]
The latest macOS build from the project releases started giving "Connection reset by peer" a couple of days ago. I built dmarchiver by myself and the issue is gone now, but I don't know what deps I used to build it.

Anyway I think I discovered the cause of it and it's not just me.

`Beginning July 25th 2019, all connections to the Twitter API (and all other Twitter domains) will require TLS 1.2`
source: https://twittercommunity.com/t/removing-support-for-legacy-tls-versions-1-0-1-1-on-twitter/126648

**Comment by de-integratie-specialisten** [comment]
Would be great if someone updated the binary. I tried building in os/x but I'm not savvy enough with python building so couldn't get it to work.

**Comment by ForbesLindesay** [comment]
My lack of familiarity with Python made building this a pain, but I did eventually manage to produce a working binary:

[dmarchiver.zip](https://github.com/Mincka/DMArchiver/files/3572116/dmarchiver.zip)

Disclaimer: all I did was try to build the existing source form this repo. I haven't made any effort to verify that it is secure/safe to use.

**Comment by de-integratie-specialisten** [comment]
Thanks! Looks like it's working.

**Comment by Mincka** [comment]
Thank you for the troubleshooting and the binary.
macos is really a pain to build proper binaries...

I finally manage myself to fix it and release an updated version:
https://github.com/Mincka/DMArchiver/releases/download/0.2.5/dmarchiver-0.2.5-macos-x86-64-TLS-Fix.zip
