### ISSUE TITLE
No longer working on Mac

### ISSUE THREAD

**Issue by eastsidewidow** [Mincka/DMArchiver#69]
I have used this a few times on Mac in 2018 and recently tried to run it again to download more recent conversations. I have used it on two machines and it simply does not work. This is the error message I get whenever I try to run it:

![Screen Shot 2019-09-18 at 9 37 14 AM](https://user-images.githubusercontent.com/47035191/65153558-f578e080-d9f7-11e9-8fcf-7d54e43a3cf7.png)

I'd love some help with this as there are messages that I really want to save. I love the tool, I'm just bummed I can't get it to work anymore.

**Comment by Mincka** [comment]
Hi,

Did you try with the updated release for macOS ?
https://github.com/Mincka/DMArchiver/releases/download/0.2.5/dmarchiver-0.2.5-macos-x86-64-TLS-Fix.zip

**Comment by eastsidewidow** [comment]
I must be blind because I genuinely did not see this. This update worked. Thank you so much!
