### ISSUE TITLE
image link is empty

### ISSUE THREAD

**Issue by cxkchengxing** [Mincka/DMArchiver#72]
i used cmd in running the dmarchive tool and i already archived my dm conversations. however, the image links does not contain any photo. is there anyway i can download the photos? 

![image](https://user-images.githubusercontent.com/62457178/77219468-ffc79300-6b70-11ea-9bfe-ad14547c3856.png)

**Comment by Mincka** [comment]
Use `-di` as an argument when running the tool and the images will be downloaded in a new folder.

**Comment by cxkchengxing** [comment]
Hi Julian,

What do you mean use -di as an argument? can you explain further? where
will i going to put “-di” im a bit slow in regards to this kind of tool.
thank you so much!

**Comment by Mincka** [comment]
Please refer to the documentation to execute the script in a Terminal or Command Prompt and the examples to use the arguments:
https://github.com/Mincka/DMArchiver/blob/master/README.md#windows
