### ISSUE TITLE
Conversation id error

### ISSUE THREAD

**Issue by ae88** [Mincka/DMArchiver#77]
When i copy the script to the console tab and press enter i get “undefined” and can’t see the id. Is there another way i can archive a specific conversation

**Comment by Mincka** [comment]
Indeed, it's broken and I don't find the conversation ID anymore in the HTML code.

I may add a switch to just extract the conversation ids in the future.

In the meantime, the easiest solution is to let the script start to download a bit of each conversation and stop the download with Ctrl-C for each. So you will get an extract of each conversation with the conversation ID as the filename.

Clearly not ideal but that's the only idea I have for the moment.

**Comment by akubaryk** [comment]
What I've found recently is that if you click on the conversation information/ground info button (top right, circled i on my browser instances), the link to "report conversation" has the conversation id at the end... has been the easiest thing for me.

**Comment by cajuncooks** [comment]
What I've found recently is that if you click on the conversation information/group info button (top right, circled i on my browser instances), the link to "report conversation" has the conversation id at the end... has been the easiest thing for me.

**Comment by ae88** [comment]
Thank you for letting me know,
Really appreciated!
