### ISSUE TITLE
Support to get reactions to message

### ISSUE THREAD

**Issue by ipimran** [Mincka/DMArchiver#79]
Is it possible to get reactions to message ?
Current response does not have any attributes which can indicate reaction to DM Message, web version shows message reactions and by which users.
This content request has to be indicated in payload or in url ?

**Comment by Mincka** [comment]
Maybe the content is already in the response. It's possible to check with `--raw-output` option.
But, how do you see it included in the text logs?
I think it could be very messy to include reactions in the log.

**Comment by ipimran** [comment]
I don't see it in raw o/p either. Web version contains `support_reactions=true` in url query, tried same in post json payload, did not work.

**Comment by ipimran** [comment]
Not feasible with current approach this flow is using. Found other ways to get that, along with more data. Thank You.

**Comment by Mincka** [comment]
Maybe you can give details for others?

**Comment by ipimran** [comment]
I attempted below request with all required headers and query params
https://api.twitter.com/1.1/dm/conversation/<conv_id>.json?query_params...

Response  was having:
min , max ids, conversation_timeline , message entries, reactions, participant details, user mentions, hashtags , attachment details ... many more objects...

All this in a fine json, easy parsing, no more html/xml handling.

**Comment by Mincka** [comment]
Ah, the API yes.
Did you reach any limit while retrieving the messages from the conversations? Not more than 30 days or 3200 messages?

When I created this tool, this was limited to 200 messages using the API.

**Comment by ipimran** [comment]
I think this is not a documented API ( I refer [here ](https://developer.twitter.com/en/docs/direct-messages/sending-and-receiving/overview)) 

My objective is little different. Not the complete dump. 
But a periodic collector job (few times a day), and feed that to a processor.
Twitter DM APIs are not fetching group DMs (may be does not support yet). 
Hence this this weird way.

**Comment by Mincka** [comment]
Ok, thanks!
